"""
菜单模板数据
- RESTAURANT_CATEGORIES: 餐厅分类（RestaurantCategory 表）
- DISH_CATEGORIES: 菜品分类（Category 表，全局）
- BRAND_INFO: 35个连锁品牌基础信息
- CHAIN_MENUS: 各品牌精准菜单（8-12道菜）
"""

# ──────────────────────────────────────────────
# 餐厅分类（首页筛选标签）
# ──────────────────────────────────────────────
RESTAURANT_CATEGORIES = [
    {'name': '西式快餐', 'icon': '🍔', 'sort_order': 1},
    {'name': '中式快餐', 'icon': '🍱', 'sort_order': 2},
    {'name': '咖啡',     'icon': '☕', 'sort_order': 3},
    {'name': '奶茶茶饮', 'icon': '🧋', 'sort_order': 4},
    {'name': '火锅',     'icon': '🍲', 'sort_order': 5},
    {'name': '日式料理', 'icon': '🍣', 'sort_order': 6},
    {'name': '意式料理', 'icon': '🍝', 'sort_order': 7},
    {'name': '面馆',     'icon': '🍜', 'sort_order': 8},
    {'name': '麻辣烫',   'icon': '🌶', 'sort_order': 9},
    {'name': '西北菜',   'icon': '🥘', 'sort_order': 10},
    {'name': '烧烤',     'icon': '🔥', 'sort_order': 11},
]

# ──────────────────────────────────────────────
# 菜品分类（餐厅内菜单分组）
# ──────────────────────────────────────────────
DISH_CATEGORIES = [
    {'name': '招牌菜',  'sort_order': 1},
    {'name': '套餐',    'sort_order': 2},
    {'name': '汉堡',    'sort_order': 3},
    {'name': '炸鸡',    'sort_order': 4},
    {'name': '披萨',    'sort_order': 5},
    {'name': '意面',    'sort_order': 6},
    {'name': '主食',    'sort_order': 7},
    {'name': '小食',    'sort_order': 8},
    {'name': '甜品',    'sort_order': 9},
    {'name': '饮料',    'sort_order': 10},
    {'name': '咖啡',    'sort_order': 11},
    {'name': '奶茶',    'sort_order': 12},
    {'name': '水果茶',  'sort_order': 13},
    {'name': '锅底',    'sort_order': 14},
    {'name': '涮品',    'sort_order': 15},
    {'name': '日式料理','sort_order': 16},
    {'name': '拉面',    'sort_order': 17},
    {'name': '乌冬',    'sort_order': 18},
    {'name': '天妇罗',  'sort_order': 19},
    {'name': '麻辣烫',  'sort_order': 20},
    {'name': '烧烤',    'sort_order': 21},
    {'name': '中式主食','sort_order': 22},
    {'name': '面食',    'sort_order': 23},
]

# ──────────────────────────────────────────────
# 品牌基础信息
# ──────────────────────────────────────────────
BRAND_INFO = {
    'kfc': {
        'name_keywords': ['肯德基'],
        'cuisine_type': '西式快餐',
        'logo_keyword': '肯德基 KFC logo',
        'delivery_fee': 5.0, 'min_order': 30.0,
        'business_hours': '09:00-23:00', 'base_rating': 4.2,
    },
    'mcdonalds': {
        'name_keywords': ['麦当劳'],
        'cuisine_type': '西式快餐',
        'logo_keyword': '麦当劳 McDonald logo',
        'delivery_fee': 5.0, 'min_order': 30.0,
        'business_hours': '09:00-23:00', 'base_rating': 4.1,
    },
    'pizzahut': {
        'name_keywords': ['必胜客'],
        'cuisine_type': '意式料理',
        'logo_keyword': '必胜客 Pizza Hut logo',
        'delivery_fee': 6.0, 'min_order': 40.0,
        'business_hours': '11:00-22:00', 'base_rating': 4.0,
    },
    'burgerking': {
        'name_keywords': ['汉堡王'],
        'cuisine_type': '西式快餐',
        'logo_keyword': '汉堡王 Burger King logo',
        'delivery_fee': 5.0, 'min_order': 30.0,
        'business_hours': '09:00-22:00', 'base_rating': 4.0,
    },
    'subway': {
        'name_keywords': ['赛百味'],
        'cuisine_type': '西式快餐',
        'logo_keyword': '赛百味 Subway logo',
        'delivery_fee': 4.0, 'min_order': 25.0,
        'business_hours': '08:00-22:00', 'base_rating': 4.0,
    },
    'wallace': {
        'name_keywords': ['华莱士'],
        'cuisine_type': '西式快餐',
        'logo_keyword': '华莱士炸鸡汉堡 logo',
        'delivery_fee': 3.0, 'min_order': 20.0,
        'business_hours': '09:00-23:00', 'base_rating': 3.8,
    },
    'starbucks': {
        'name_keywords': ['星巴克'],
        'cuisine_type': '咖啡',
        'logo_keyword': '星巴克 Starbucks logo',
        'delivery_fee': 6.0, 'min_order': 30.0,
        'business_hours': '08:00-22:00', 'base_rating': 4.4,
    },
    'luckin': {
        'name_keywords': ['瑞幸咖啡', '瑞幸'],
        'cuisine_type': '咖啡',
        'logo_keyword': '瑞幸咖啡 Luckin logo',
        'delivery_fee': 4.0, 'min_order': 20.0,
        'business_hours': '08:00-22:00', 'base_rating': 4.2,
    },
    'manner': {
        'name_keywords': ['Manner', 'MANNER'],
        'cuisine_type': '咖啡',
        'logo_keyword': 'Manner Coffee logo',
        'delivery_fee': 5.0, 'min_order': 25.0,
        'business_hours': '08:00-21:00', 'base_rating': 4.5,
    },
    'timhortons': {
        'name_keywords': ['Tim Hortons', 'Tims咖啡'],
        'cuisine_type': '咖啡',
        'logo_keyword': 'Tim Hortons Tims logo',
        'delivery_fee': 5.0, 'min_order': 25.0,
        'business_hours': '08:00-22:00', 'base_rating': 4.1,
    },
    'heytea': {
        'name_keywords': ['喜茶'],
        'cuisine_type': '奶茶茶饮',
        'logo_keyword': '喜茶 HEYTEA logo',
        'delivery_fee': 4.0, 'min_order': 20.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.5,
    },
    'nayuki': {
        'name_keywords': ['奈雪的茶', '奈雪'],
        'cuisine_type': '奶茶茶饮',
        'logo_keyword': '奈雪的茶 Nayuki logo',
        'delivery_fee': 5.0, 'min_order': 25.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.4,
    },
    'chabackao': {
        'name_keywords': ['茶百道'],
        'cuisine_type': '奶茶茶饮',
        'logo_keyword': '茶百道奶茶 logo',
        'delivery_fee': 3.0, 'min_order': 15.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.2,
    },
    'mixue': {
        'name_keywords': ['蜜雪冰城'],
        'cuisine_type': '奶茶茶饮',
        'logo_keyword': '蜜雪冰城 logo',
        'delivery_fee': 2.0, 'min_order': 12.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.0,
    },
    'coco': {
        'name_keywords': ['CoCo都可', 'COCO都可', 'coco都可'],
        'cuisine_type': '奶茶茶饮',
        'logo_keyword': 'CoCo都可奶茶 logo',
        'delivery_fee': 3.0, 'min_order': 15.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.1,
    },
    'shuyi': {
        'name_keywords': ['书亦烧仙草'],
        'cuisine_type': '奶茶茶饮',
        'logo_keyword': '书亦烧仙草奶茶 logo',
        'delivery_fee': 3.0, 'min_order': 15.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.1,
    },
    'yiheetang': {
        'name_keywords': ['益禾堂'],
        'cuisine_type': '奶茶茶饮',
        'logo_keyword': '益禾堂奶茶 logo',
        'delivery_fee': 3.0, 'min_order': 15.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.0,
    },
    'guming': {
        'name_keywords': ['古茗'],
        'cuisine_type': '奶茶茶饮',
        'logo_keyword': '古茗奶茶 logo',
        'delivery_fee': 3.0, 'min_order': 15.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.1,
    },
    'haidilao': {
        'name_keywords': ['海底捞'],
        'cuisine_type': '火锅',
        'logo_keyword': '海底捞火锅 logo',
        'delivery_fee': 8.0, 'min_order': 80.0,
        'business_hours': '11:00-02:00', 'base_rating': 4.6,
    },
    'xiabu': {
        'name_keywords': ['呷哺呷哺'],
        'cuisine_type': '火锅',
        'logo_keyword': '呷哺呷哺 logo',
        'delivery_fee': 6.0, 'min_order': 50.0,
        'business_hours': '11:00-22:00', 'base_rating': 4.1,
    },
    'xiaolongkan': {
        'name_keywords': ['小龙坎'],
        'cuisine_type': '火锅',
        'logo_keyword': '小龙坎火锅 logo',
        'delivery_fee': 8.0, 'min_order': 80.0,
        'business_hours': '11:00-23:00', 'base_rating': 4.3,
    },
    'coucou': {
        'name_keywords': ['凑凑'],
        'cuisine_type': '火锅',
        'logo_keyword': '凑凑火锅 logo',
        'delivery_fee': 8.0, 'min_order': 80.0,
        'business_hours': '11:00-22:00', 'base_rating': 4.4,
    },
    'yoshinoya': {
        'name_keywords': ['吉野家'],
        'cuisine_type': '日式料理',
        'logo_keyword': '吉野家 Yoshinoya logo',
        'delivery_fee': 4.0, 'min_order': 25.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.0,
    },
    'ajisen': {
        'name_keywords': ['味千拉面', '味千'],
        'cuisine_type': '日式料理',
        'logo_keyword': '味千拉面 Ajisen logo',
        'delivery_fee': 5.0, 'min_order': 30.0,
        'business_hours': '11:00-22:00', 'base_rating': 4.0,
    },
    'marugame': {
        'name_keywords': ['丸龟制面', '丸亀'],
        'cuisine_type': '日式料理',
        'logo_keyword': '丸龟制面乌冬 logo',
        'delivery_fee': 4.0, 'min_order': 25.0,
        'business_hours': '11:00-22:00', 'base_rating': 4.2,
    },
    'saizeriya': {
        'name_keywords': ['萨莉亚'],
        'cuisine_type': '意式料理',
        'logo_keyword': '萨莉亚 Saizeriya logo',
        'delivery_fee': 5.0, 'min_order': 35.0,
        'business_hours': '11:00-22:00', 'base_rating': 4.1,
    },
    'kungfu': {
        'name_keywords': ['真功夫'],
        'cuisine_type': '中式快餐',
        'logo_keyword': '真功夫中式快餐 logo',
        'delivery_fee': 3.0, 'min_order': 20.0,
        'business_hours': '08:00-22:00', 'base_rating': 3.9,
    },
    'laoxiangji': {
        'name_keywords': ['老乡鸡'],
        'cuisine_type': '中式快餐',
        'logo_keyword': '老乡鸡快餐 logo',
        'delivery_fee': 3.0, 'min_order': 20.0,
        'business_hours': '09:00-22:00', 'base_rating': 4.0,
    },
    'damixiansheng': {
        'name_keywords': ['大米先生'],
        'cuisine_type': '中式快餐',
        'logo_keyword': '大米先生快餐 logo',
        'delivery_fee': 3.0, 'min_order': 20.0,
        'business_hours': '09:00-22:00', 'base_rating': 3.9,
    },
    'countrystyle': {
        'name_keywords': ['乡村基'],
        'cuisine_type': '中式快餐',
        'logo_keyword': '乡村基中式快餐 logo',
        'delivery_fee': 3.0, 'min_order': 20.0,
        'business_hours': '09:00-22:00', 'base_rating': 3.9,
    },
    'yanggf': {
        'name_keywords': ['杨国福麻辣烫', '杨国福'],
        'cuisine_type': '麻辣烫',
        'logo_keyword': '杨国福麻辣烫 logo',
        'delivery_fee': 3.0, 'min_order': 20.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.0,
    },
    'zhangliang': {
        'name_keywords': ['张亮麻辣烫', '张亮'],
        'cuisine_type': '麻辣烫',
        'logo_keyword': '张亮麻辣烫 logo',
        'delivery_fee': 3.0, 'min_order': 20.0,
        'business_hours': '10:00-22:00', 'base_rating': 3.9,
    },
    'hefu': {
        'name_keywords': ['和府捞面'],
        'cuisine_type': '面馆',
        'logo_keyword': '和府捞面 logo',
        'delivery_fee': 4.0, 'min_order': 25.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.2,
    },
    'yujian': {
        'name_keywords': ['遇见小面'],
        'cuisine_type': '面馆',
        'logo_keyword': '遇见小面重庆 logo',
        'delivery_fee': 3.0, 'min_order': 20.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.1,
    },
    'wuye': {
        'name_keywords': ['五爷拌面'],
        'cuisine_type': '面馆',
        'logo_keyword': '五爷拌面 logo',
        'delivery_fee': 3.0, 'min_order': 18.0,
        'business_hours': '10:00-22:00', 'base_rating': 4.0,
    },
    'xibei': {
        'name_keywords': ['西贝', '西贝莜面村'],
        'cuisine_type': '西北菜',
        'logo_keyword': '西贝莜面村 logo',
        'delivery_fee': 6.0, 'min_order': 50.0,
        'business_hours': '11:00-22:00', 'base_rating': 4.3,
    },
    'muwu': {
        'name_keywords': ['木屋烧烤'],
        'cuisine_type': '烧烤',
        'logo_keyword': '木屋烧烤 logo',
        'delivery_fee': 6.0, 'min_order': 50.0,
        'business_hours': '17:00-01:00', 'base_rating': 4.2,
    },
}

# ──────────────────────────────────────────────
# 各品牌精准菜单
# 每道菜字段：name, description, price, category, is_recommended, is_spicy, ingredients, image_keyword
# ──────────────────────────────────────────────
CHAIN_MENUS = {

    'kfc': [
        {'name': '原味鸡', 'description': '秘方腌制，外酥里嫩，经典不变', 'price': 14.0, 'category': '炸鸡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡腿肉', 'image_keyword': '肯德基原味鸡'},
        {'name': '劲脆鸡腿堡', 'description': '脆皮鸡腿+新鲜生菜，口感丰富', 'price': 22.0, 'category': '汉堡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡腿肉、生菜、蛋黄酱', 'image_keyword': '肯德基劲脆鸡腿堡'},
        {'name': '香辣鸡腿堡', 'description': '辣味腌制鸡腿，麻辣鲜香', 'price': 22.0, 'category': '汉堡', 'is_recommended': False, 'is_spicy': True, 'ingredients': '鸡腿肉、辣椒', 'image_keyword': '肯德基香辣鸡腿堡'},
        {'name': '老北京鸡肉卷', 'description': '甜面酱+黄瓜+鸡肉，京味十足', 'price': 17.0, 'category': '汉堡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡肉、黄瓜、甜面酱', 'image_keyword': '肯德基老北京鸡肉卷'},
        {'name': '鸡米花（中）', 'description': '嫩滑鸡肉粒，一口一个停不下来', 'price': 16.0, 'category': '炸鸡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡胸肉', 'image_keyword': '肯德基鸡米花'},
        {'name': '劲辣鸡翅', 'description': '香辣入味，骨肉分离更好吃', 'price': 12.0, 'category': '炸鸡', 'is_recommended': False, 'is_spicy': True, 'ingredients': '鸡翅', 'image_keyword': '肯德基辣鸡翅'},
        {'name': '薯条（中）', 'description': '金黄酥脆，撒上盐花刚刚好', 'price': 12.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '马铃薯', 'image_keyword': '肯德基薯条'},
        {'name': '蛋挞', 'description': '酥皮蛋挞，奶香浓郁，现烤现卖', 'price': 7.0, 'category': '甜品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡蛋、面粉、牛奶', 'image_keyword': '肯德基蛋挞'},
        {'name': '双人套餐', 'description': '2块原味鸡+2个汉堡+2份薯条+2杯饮料', 'price': 69.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡肉、面包、马铃薯', 'image_keyword': '肯德基双人套餐'},
        {'name': '百事可乐（中）', 'description': '冰爽可乐，清凉解渴', 'price': 8.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '碳酸饮料', 'image_keyword': '百事可乐'},
    ],

    'mcdonalds': [
        {'name': '巨无霸', 'description': '双层牛肉饼+特调酱料，经典之选', 'price': 24.0, 'category': '汉堡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉饼、生菜、洋葱', 'image_keyword': '麦当劳巨无霸'},
        {'name': '麦辣鸡腿堡', 'description': '香辣鸡腿肉，嫩滑多汁', 'price': 22.0, 'category': '汉堡', 'is_recommended': True, 'is_spicy': True, 'ingredients': '鸡腿肉、辣椒', 'image_keyword': '麦当劳麦辣鸡腿堡'},
        {'name': '麦香鱼', 'description': '香嫩鱼排+塔塔酱，清新不腻', 'price': 16.0, 'category': '汉堡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鱼排、塔塔酱', 'image_keyword': '麦当劳麦香鱼'},
        {'name': '麦辣鸡翅', 'description': '香辣脆皮鸡翅，外焦里嫩', 'price': 13.5, 'category': '炸鸡', 'is_recommended': True, 'is_spicy': True, 'ingredients': '鸡翅', 'image_keyword': '麦当劳麦辣鸡翅'},
        {'name': '麦乐鸡（9块）', 'description': '金黄酥脆，搭配蘸酱更美味', 'price': 17.0, 'category': '炸鸡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡胸肉', 'image_keyword': '麦当劳麦乐鸡'},
        {'name': '薯条（中）', 'description': '黄金薯条，酥脆热辣', 'price': 12.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '马铃薯', 'image_keyword': '麦当劳薯条'},
        {'name': '圆筒冰淇淋', 'description': '香草味冰淇淋，甜而不腻', 'price': 4.0, 'category': '甜品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛奶、糖', 'image_keyword': '麦当劳圆筒冰淇淋'},
        {'name': '草莓麦旋风', 'description': '草莓酱与冰淇淋的完美融合', 'price': 16.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '冰淇淋、草莓酱', 'image_keyword': '麦当劳麦旋风'},
        {'name': '巨无霸套餐', 'description': '巨无霸+中薯条+中可乐', 'price': 33.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、马铃薯', 'image_keyword': '麦当劳套餐'},
        {'name': '可口可乐（中）', 'description': '经典可乐，畅爽冰凉', 'price': 9.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '碳酸饮料', 'image_keyword': '可口可乐'},
    ],

    'pizzahut': [
        {'name': '超级至尊披萨（12寸）', 'description': '牛肉、香肠、蘑菇、青椒，料足味美', 'price': 129.0, 'category': '披萨', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、香肠、蘑菇', 'image_keyword': '必胜客超级至尊披萨'},
        {'name': '培根双层牛肉披萨（12寸）', 'description': '双层牛肉饼底，培根加倍满足', 'price': 149.0, 'category': '披萨', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、培根', 'image_keyword': '必胜客牛肉披萨'},
        {'name': '夏威夷披萨（8寸）', 'description': '菠萝+火腿，甜咸交融的经典口味', 'price': 59.0, 'category': '披萨', 'is_recommended': False, 'is_spicy': False, 'ingredients': '菠萝、火腿', 'image_keyword': '必胜客夏威夷披萨'},
        {'name': '奶油培根意大利面', 'description': '浓郁奶油酱汁，搭配脆培根', 'price': 52.0, 'category': '意面', 'is_recommended': True, 'is_spicy': False, 'ingredients': '意面、培根、奶油', 'image_keyword': '必胜客奶油培根意面'},
        {'name': '意式肉酱面', 'description': '番茄肉酱慢炖，经典意式风味', 'price': 48.0, 'category': '意面', 'is_recommended': False, 'is_spicy': False, 'ingredients': '意面、牛肉肉酱', 'image_keyword': '必胜客肉酱意面'},
        {'name': '香蒜面包', 'description': '黄油蒜香面包，外酥内软', 'price': 22.0, 'category': '小食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '面包、黄油、大蒜', 'image_keyword': '必胜客香蒜面包'},
        {'name': '莫扎里拉芝士条', 'description': '拉丝芝士，蘸番茄酱超满足', 'price': 28.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芝士', 'image_keyword': '必胜客芝士条'},
        {'name': '熔岩巧克力', 'description': '外层微酥，内心巧克力浆热流而出', 'price': 28.0, 'category': '甜品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '巧克力、面粉', 'image_keyword': '熔岩巧克力蛋糕'},
        {'name': '百事可乐', 'description': '冰爽碳酸饮料', 'price': 12.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '碳酸饮料', 'image_keyword': '百事可乐'},
        {'name': '双人超值套餐', 'description': '9寸披萨+意面+2杯饮料+小食', 'price': 128.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '披萨、意面', 'image_keyword': '必胜客双人套餐'},
    ],

    'burgerking': [
        {'name': '皇堡', 'description': '火烤牛肉饼，皇堡经典之味', 'price': 24.0, 'category': '汉堡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉饼、生菜、番茄', 'image_keyword': '汉堡王皇堡'},
        {'name': '双层皇堡', 'description': '双层火烤牛肉饼，满足加倍', 'price': 32.0, 'category': '汉堡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉饼×2、生菜', 'image_keyword': '汉堡王双层皇堡'},
        {'name': '辣椒华堡', 'description': '加入墨西哥辣椒，风味独特', 'price': 28.0, 'category': '汉堡', 'is_recommended': False, 'is_spicy': True, 'ingredients': '牛肉饼、辣椒', 'image_keyword': '汉堡王辣椒华堡'},
        {'name': '脆皮鸡块（9块）', 'description': '外酥里嫩，鸡肉鲜嫩多汁', 'price': 22.0, 'category': '炸鸡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡胸肉', 'image_keyword': '汉堡王脆皮鸡块'},
        {'name': '辣鸡翅（2个）', 'description': '香辣鸡翅，骨肉分离', 'price': 12.0, 'category': '炸鸡', 'is_recommended': False, 'is_spicy': True, 'ingredients': '鸡翅', 'image_keyword': '汉堡王辣鸡翅'},
        {'name': '薯条（中）', 'description': '细长酥脆，金黄诱人', 'price': 11.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '马铃薯', 'image_keyword': '汉堡王薯条'},
        {'name': '洋葱圈', 'description': '酥脆洋葱圈，蘸酱更美味', 'price': 10.0, 'category': '小食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '洋葱', 'image_keyword': '汉堡王洋葱圈'},
        {'name': '圣代冰淇淋', 'description': '香草冰淇淋，清凉甜蜜', 'price': 9.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '牛奶、糖', 'image_keyword': '汉堡王圣代'},
        {'name': '皇堡套餐', 'description': '皇堡+中薯条+中可乐', 'price': 33.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、马铃薯', 'image_keyword': '汉堡王套餐'},
        {'name': '可乐（中）', 'description': '冰爽可乐，搭配汉堡绝配', 'price': 8.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '碳酸饮料', 'image_keyword': '可口可乐'},
    ],

    'subway': [
        {'name': '意大利风味（6英寸）', 'description': '萨拉米香肠+配料，经典意式风味', 'price': 33.0, 'category': '主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '萨拉米肠、蔬菜', 'image_keyword': '赛百味三明治'},
        {'name': '黑椒牛肉（6英寸）', 'description': '嫩滑牛肉片+黑胡椒酱，香辣可口', 'price': 36.0, 'category': '主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉片、黑胡椒', 'image_keyword': '赛百味黑椒牛肉'},
        {'name': '烤鸡（6英寸）', 'description': '烟熏烤鸡肉，低脂高蛋白', 'price': 35.0, 'category': '主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '烤鸡肉', 'image_keyword': '赛百味烤鸡三明治'},
        {'name': '金枪鱼（6英寸）', 'description': '鲜美金枪鱼+蛋黄酱，清爽不腻', 'price': 35.0, 'category': '主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '金枪鱼、蛋黄酱', 'image_keyword': '赛百味金枪鱼'},
        {'name': '黑椒牛肉（一英尺）', 'description': '加量一英尺，满足大胃口', 'price': 55.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉片、黑胡椒', 'image_keyword': '赛百味一英尺三明治'},
        {'name': '烤鸡套餐', 'description': '6英寸烤鸡+薯片+饮料', 'price': 45.0, 'category': '套餐', 'is_recommended': False, 'is_spicy': False, 'ingredients': '烤鸡肉', 'image_keyword': '赛百味套餐'},
        {'name': '燕麦饼干', 'description': '香酥燕麦饼干，健康美味', 'price': 6.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '燕麦、糖', 'image_keyword': '燕麦饼干'},
        {'name': '可乐', 'description': '冰爽碳酸饮料', 'price': 6.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '碳酸饮料', 'image_keyword': '可口可乐'},
    ],

    'wallace': [
        {'name': '劲脆鸡腿堡', 'description': '脆皮鸡腿，价格实惠，好吃不贵', 'price': 9.9, 'category': '汉堡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡腿肉', 'image_keyword': '华莱士鸡腿堡'},
        {'name': '香辣鸡腿堡', 'description': '麻辣鸡腿，辣味上头', 'price': 10.9, 'category': '汉堡', 'is_recommended': False, 'is_spicy': True, 'ingredients': '鸡腿肉、辣椒', 'image_keyword': '华莱士香辣鸡腿堡'},
        {'name': '新奥尔良鸡腿堡', 'description': '新奥尔良风味腌制，甜辣适中', 'price': 10.9, 'category': '汉堡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡腿肉', 'image_keyword': '华莱士新奥尔良'},
        {'name': '香辣鸡翅（2个）', 'description': '性价比超高的香辣鸡翅', 'price': 9.8, 'category': '炸鸡', 'is_recommended': True, 'is_spicy': True, 'ingredients': '鸡翅', 'image_keyword': '华莱士鸡翅'},
        {'name': '鸡腿（1个）', 'description': '整只鸡腿，肉多过瘾', 'price': 6.9, 'category': '炸鸡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡腿', 'image_keyword': '炸鸡腿'},
        {'name': '薯条（大）', 'description': '酥脆薯条，量大实惠', 'price': 7.9, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '马铃薯', 'image_keyword': '薯条'},
        {'name': '双人套餐', 'description': '2个鸡腿堡+2份薯条+2杯饮料', 'price': 38.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡腿肉、马铃薯', 'image_keyword': '华莱士套餐'},
        {'name': '可乐', 'description': '清爽碳酸饮料', 'price': 4.9, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '碳酸饮料', 'image_keyword': '可口可乐'},
    ],

    'starbucks': [
        {'name': '拿铁（大杯）', 'description': '浓缩咖啡+绵密奶泡，香醇平衡', 'price': 34.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '浓缩咖啡、牛奶', 'image_keyword': '星巴克拿铁'},
        {'name': '美式（大杯）', 'description': '纯粹咖啡风味，清爽醒神', 'price': 28.0, 'category': '咖啡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '浓缩咖啡', 'image_keyword': '星巴克美式咖啡'},
        {'name': '焦糖玛奇朵（大杯）', 'description': '香草奶泡+焦糖淋酱，甜而不腻', 'price': 39.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '咖啡、焦糖、牛奶', 'image_keyword': '星巴克焦糖玛奇朵'},
        {'name': '摩卡（大杯）', 'description': '咖啡与巧克力的完美融合', 'price': 37.0, 'category': '咖啡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '咖啡、巧克力', 'image_keyword': '星巴克摩卡'},
        {'name': '抹茶拿铁（大杯）', 'description': '日式抹茶粉+醇香牛奶', 'price': 37.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '抹茶、牛奶', 'image_keyword': '星巴克抹茶拿铁'},
        {'name': '抹茶星冰乐', 'description': '冰沙口感，抹茶清香，夏日必备', 'price': 39.0, 'category': '饮料', 'is_recommended': True, 'is_spicy': False, 'ingredients': '抹茶、冰、牛奶', 'image_keyword': '星巴克抹茶星冰乐'},
        {'name': '焦糖星冰乐', 'description': '咖啡冰沙淋焦糖，香甜爽口', 'price': 41.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '咖啡、焦糖、冰', 'image_keyword': '星巴克焦糖星冰乐'},
        {'name': '柠檬磅蛋糕', 'description': '酸甜柠檬糖霜，配咖啡绝配', 'price': 26.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '柠檬、面粉', 'image_keyword': '星巴克柠檬蛋糕'},
        {'name': '布朗尼', 'description': '浓郁巧克力口感，软糯扎实', 'price': 28.0, 'category': '甜品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '巧克力、面粉', 'image_keyword': '星巴克布朗尼'},
        {'name': '卡布奇诺（大杯）', 'description': '丝滑奶泡覆盖浓缩咖啡', 'price': 34.0, 'category': '咖啡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '咖啡、牛奶', 'image_keyword': '星巴克卡布奇诺'},
    ],

    'luckin': [
        {'name': '生椰拿铁（大）', 'description': '椰乳+浓缩咖啡，椰香清甜', 'price': 19.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '椰浆、咖啡', 'image_keyword': '瑞幸生椰拿铁'},
        {'name': '厚乳拿铁（大）', 'description': '厚实奶香，浓而不腻', 'price': 17.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '厚乳、咖啡', 'image_keyword': '瑞幸厚乳拿铁'},
        {'name': '美式（大）', 'description': '醒神提神，咖啡本味', 'price': 11.0, 'category': '咖啡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '浓缩咖啡', 'image_keyword': '瑞幸美式咖啡'},
        {'name': '丝绒拿铁（大）', 'description': '天鹅绒般丝滑口感', 'price': 19.0, 'category': '咖啡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '咖啡、牛奶', 'image_keyword': '瑞幸丝绒拿铁'},
        {'name': '茉莉花茶拿铁（大）', 'description': '茉莉花茶香+奶香，清新雅致', 'price': 16.0, 'category': '饮料', 'is_recommended': True, 'is_spicy': False, 'ingredients': '茉莉花茶、牛奶', 'image_keyword': '瑞幸茉莉花茶拿铁'},
        {'name': '杨枝甘露（大）', 'description': '芒果+椰浆+西柚，清甜解暑', 'price': 19.0, 'category': '饮料', 'is_recommended': True, 'is_spicy': False, 'ingredients': '芒果、椰浆、西柚', 'image_keyword': '瑞幸杨枝甘露'},
        {'name': '冰摇橙汁美式（大）', 'description': '鲜橙果汁+浓缩咖啡，酸甜醒神', 'price': 15.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '橙汁、咖啡', 'image_keyword': '瑞幸橙汁美式'},
        {'name': '可颂', 'description': '奶香酥皮，层次丰富', 'price': 10.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '面粉、黄油', 'image_keyword': '牛角可颂面包'},
        {'name': '法式软包', 'description': '软糯面包，早餐搭配咖啡刚好', 'price': 9.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '面粉、黄油', 'image_keyword': '法式软包面包'},
    ],

    'manner': [
        {'name': '拿铁（大）', 'description': '精品咖啡豆+新鲜牛奶，醇厚均衡', 'price': 15.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '精品咖啡豆、牛奶', 'image_keyword': 'Manner拿铁咖啡'},
        {'name': '美式（大）', 'description': '单品豆手冲，干净纯粹', 'price': 12.0, 'category': '咖啡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '精品咖啡豆', 'image_keyword': 'Manner美式咖啡'},
        {'name': '燕麦拿铁（大）', 'description': '燕麦奶替代牛奶，清爽健康', 'price': 17.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '咖啡、燕麦奶', 'image_keyword': '燕麦拿铁咖啡'},
        {'name': '生椰拿铁（大）', 'description': '椰浆与咖啡的夏日组合', 'price': 19.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '咖啡、椰浆', 'image_keyword': '生椰拿铁咖啡'},
        {'name': '蜜桃乌龙拿铁（大）', 'description': '乌龙茶香+蜜桃果香，创意饮品', 'price': 20.0, 'category': '饮料', 'is_recommended': True, 'is_spicy': False, 'ingredients': '乌龙茶、蜜桃', 'image_keyword': '蜜桃乌龙拿铁'},
        {'name': '手冲咖啡', 'description': '单品豆现磨手冲，风味独特', 'price': 22.0, 'category': '咖啡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '单品咖啡豆', 'image_keyword': '手冲咖啡'},
        {'name': '可颂', 'description': '黄油酥皮可颂，搭配咖啡完美', 'price': 12.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '面粉、黄油', 'image_keyword': '牛角可颂面包'},
        {'name': '芝士面包', 'description': '浓郁芝士内馅，软糯拉丝', 'price': 10.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '面粉、芝士', 'image_keyword': '芝士面包'},
    ],

    'timhortons': [
        {'name': '原味咖啡（中）', 'description': '加拿大国民咖啡，百年经典配方', 'price': 14.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '咖啡', 'image_keyword': 'Tim Hortons咖啡'},
        {'name': '拿铁（中）', 'description': '浓缩+蒸汽牛奶，香醇顺滑', 'price': 24.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '咖啡、牛奶', 'image_keyword': 'Tim Hortons拿铁'},
        {'name': '冰卡布（中）', 'description': '冰镇卡布奇诺，夏日清凉', 'price': 24.0, 'category': '咖啡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '咖啡、牛奶', 'image_keyword': 'Tims冰卡布'},
        {'name': '伯爵奶茶（中）', 'description': '伯爵红茶+奶香，英伦风味', 'price': 22.0, 'category': '饮料', 'is_recommended': True, 'is_spicy': False, 'ingredients': '伯爵茶、牛奶', 'image_keyword': '伯爵奶茶'},
        {'name': '原味甜甜圈', 'description': '松软甜甜圈，经典不变', 'price': 8.0, 'category': '甜品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '面粉、糖', 'image_keyword': '甜甜圈'},
        {'name': '枫糖甜甜圈', 'description': '枫糖淋酱，加拿大风味', 'price': 9.0, 'category': '甜品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '面粉、枫糖', 'image_keyword': '枫糖甜甜圈'},
        {'name': '蓝莓马芬', 'description': '新鲜蓝莓颗粒，松软湿润', 'price': 12.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '蓝莓、面粉', 'image_keyword': '蓝莓马芬'},
        {'name': '贝果', 'description': '口感扎实，搭配奶油芝士', 'price': 14.0, 'category': '主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '面粉', 'image_keyword': '贝果面包'},
        {'name': '热可可（中）', 'description': '香浓热可可，冬日暖饮', 'price': 16.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '可可粉、牛奶', 'image_keyword': '热可可'},
    ],

    'heytea': [
        {'name': '多肉葡萄', 'description': '新鲜葡萄+芝士奶盖，爆汁多肉', 'price': 23.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '葡萄、芝士', 'image_keyword': '喜茶多肉葡萄'},
        {'name': '多肉芒芒甘露', 'description': '芒果果肉+椰浆，热带风情', 'price': 23.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '芒果、椰浆', 'image_keyword': '喜茶芒芒甘露'},
        {'name': '芝芝桃桃', 'description': '水蜜桃+芝士奶盖，清甜细腻', 'price': 22.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '水蜜桃、芝士', 'image_keyword': '喜茶芝芝桃桃'},
        {'name': '波波冰', 'description': '波波珍珠+芝士奶盖+绿茶', 'price': 19.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '珍珠、绿茶', 'image_keyword': '喜茶波波冰'},
        {'name': '芝芝茉莉', 'description': '茉莉绿茶+芝士奶盖，清香雅致', 'price': 22.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '茉莉茶、芝士', 'image_keyword': '喜茶芝芝茉莉'},
        {'name': '纯绿茶', 'description': '原叶绿茶，清爽回甘', 'price': 11.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '绿茶', 'image_keyword': '绿茶'},
        {'name': '芝芝美式', 'description': '美式咖啡+芝士奶盖，咖啡控必点', 'price': 19.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '咖啡、芝士', 'image_keyword': '喜茶芝芝美式'},
        {'name': '软欧包', 'description': '现烤软欧，外酥内软', 'price': 16.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '面粉、黄油', 'image_keyword': '软欧包'},
        {'name': '多肉脆脆', 'description': '果肉+脆脆颗粒，口感丰富', 'price': 21.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '水果、脆粒', 'image_keyword': '喜茶多肉脆脆'},
    ],

    'nayuki': [
        {'name': '霸气芝士草莓', 'description': '新鲜草莓+芝士奶盖，酸甜浓香', 'price': 26.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '草莓、芝士', 'image_keyword': '奈雪芝士草莓'},
        {'name': '霸气芒果', 'description': '新鲜芒果大块切，果汁饱满', 'price': 26.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '芒果', 'image_keyword': '奈雪芒果'},
        {'name': '霸气白桃', 'description': '白桃果茶+芝士奶盖，清甜可口', 'price': 25.0, 'category': '水果茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '白桃', 'image_keyword': '奈雪白桃茶'},
        {'name': '鸭屎香宝藏茶', 'description': '凤凰单枞鸭屎香，岩韵十足', 'price': 22.0, 'category': '奶茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '单枞茶', 'image_keyword': '奈雪鸭屎香'},
        {'name': '牛乳茶', 'description': '原叶茶+鲜牛乳，简单纯粹', 'price': 20.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '红茶、牛奶', 'image_keyword': '奈雪牛乳茶'},
        {'name': '原味软欧包', 'description': '现烤软欧包，麦香浓郁', 'price': 18.0, 'category': '甜品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '面粉、黄油', 'image_keyword': '软欧包'},
        {'name': '芝士软欧包', 'description': '芝士夹心，拉丝满满', 'price': 20.0, 'category': '甜品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '面粉、芝士', 'image_keyword': '芝士软欧包'},
        {'name': '马卡龙（3个）', 'description': '法式马卡龙，色彩缤纷，口感细腻', 'price': 22.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '杏仁粉、糖', 'image_keyword': '马卡龙'},
        {'name': '肉桂卷', 'description': '肉桂糖霜卷，香甜软糯', 'price': 18.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '面粉、肉桂', 'image_keyword': '肉桂卷'},
    ],

    'chabackao': [
        {'name': '杨枝甘露', 'description': '芒果+西柚+椰浆，网红经典款', 'price': 18.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '芒果、椰浆', 'image_keyword': '杨枝甘露奶茶'},
        {'name': '冰淇淋奶茶', 'description': '奶茶上放一球冰淇淋，超治愈', 'price': 16.0, 'category': '奶茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '奶茶、冰淇淋', 'image_keyword': '冰淇淋奶茶'},
        {'name': '生椰拿铁', 'description': '椰浆+咖啡，茶百道版生椰', 'price': 19.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '椰浆、咖啡', 'image_keyword': '生椰拿铁'},
        {'name': '珍珠奶茶（大）', 'description': '黑糖珍珠+浓香奶茶', 'price': 12.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '珍珠、奶茶', 'image_keyword': '珍珠奶茶'},
        {'name': '芋圆奶茶', 'description': '手工芋圆+奶茶，Q弹满足', 'price': 14.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芋圆、奶茶', 'image_keyword': '芋圆奶茶'},
        {'name': '柠檬茶', 'description': '鲜柠檬+红茶，清爽解腻', 'price': 12.0, 'category': '水果茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '柠檬、红茶', 'image_keyword': '柠檬茶'},
        {'name': '西瓜汁', 'description': '新鲜西瓜现榨，夏日消暑', 'price': 15.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '西瓜', 'image_keyword': '西瓜汁'},
        {'name': '美式咖啡', 'description': '提神醒脑，清爽不苦', 'price': 10.0, 'category': '咖啡', 'is_recommended': False, 'is_spicy': False, 'ingredients': '咖啡', 'image_keyword': '美式咖啡'},
    ],

    'mixue': [
        {'name': '冰鲜柠檬水', 'description': '4元的快乐，鲜柠檬+冰水', 'price': 4.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '柠檬、冰', 'image_keyword': '蜜雪冰城柠檬水'},
        {'name': '珍珠奶茶', 'description': '黑糖珍珠+浓香奶茶，7元的幸福', 'price': 7.0, 'category': '奶茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '珍珠、奶茶', 'image_keyword': '蜜雪冰城珍珠奶茶'},
        {'name': '草莓奶昔', 'description': '浓郁草莓+冰淇淋，甜蜜满足', 'price': 8.0, 'category': '奶茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '草莓、奶', 'image_keyword': '蜜雪冰城草莓奶昔'},
        {'name': '芒果奶昔', 'description': '芒果+奶香浓郁，热带风情', 'price': 9.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芒果、奶', 'image_keyword': '芒果奶昔'},
        {'name': '奥利奥奶昔', 'description': '奥利奥碎+奶昔，饼干控必点', 'price': 9.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '奥利奥、奶', 'image_keyword': '奥利奥奶昔'},
        {'name': '冰淇淋', 'description': '2元的简单快乐', 'price': 2.0, 'category': '甜品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛奶、糖', 'image_keyword': '冰淇淋甜筒'},
        {'name': '甜筒（草莓味）', 'description': '草莓风味冰淇淋甜筒', 'price': 3.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '草莓、牛奶', 'image_keyword': '草莓甜筒'},
        {'name': '椰浆芒果', 'description': '椰浆+芒果，清甜热带风', 'price': 8.0, 'category': '水果茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '椰浆、芒果', 'image_keyword': '椰浆芒果饮料'},
    ],

    'coco': [
        {'name': '波霸奶茶（大）', 'description': '大颗黑糖波霸+浓郁奶茶', 'price': 14.0, 'category': '奶茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '波霸珍珠、奶茶', 'image_keyword': 'CoCo波霸奶茶'},
        {'name': '百香果绿茶（大）', 'description': '酸甜百香果+清爽绿茶', 'price': 13.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '百香果、绿茶', 'image_keyword': 'CoCo百香果绿茶'},
        {'name': '多肉葡萄（大）', 'description': '新鲜葡萄果肉+茶底', 'price': 16.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '葡萄', 'image_keyword': 'CoCo多肉葡萄'},
        {'name': '奶绿（大）', 'description': '绿茶+奶香，清爽解腻', 'price': 13.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '绿茶、奶精', 'image_keyword': '奶绿奶茶'},
        {'name': '椰椰芒芒（大）', 'description': '椰浆+芒果，夏日热带风味', 'price': 17.0, 'category': '水果茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '椰浆、芒果', 'image_keyword': '椰浆芒果奶茶'},
        {'name': '豆浆奶茶（大）', 'description': '豆香+茶香，健康清甜', 'price': 14.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '豆浆、红茶', 'image_keyword': '豆浆奶茶'},
        {'name': '布丁', 'description': '嫩滑焦糖布丁，加料首选', 'price': 4.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡蛋、牛奶', 'image_keyword': '焦糖布丁'},
        {'name': '芋圆（加料）', 'description': '手工芋圆，Q弹有嚼劲', 'price': 3.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芋头', 'image_keyword': '芋圆'},
    ],

    'shuyi': [
        {'name': '原味烧仙草', 'description': '书亦招牌，仙草冻+奶香底料', 'price': 10.0, 'category': '奶茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '仙草、奶', 'image_keyword': '书亦烧仙草'},
        {'name': '芋圆烧仙草', 'description': '芋圆+仙草，双重Q弹', 'price': 13.0, 'category': '奶茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '仙草、芋圆', 'image_keyword': '芋圆烧仙草'},
        {'name': '满杯红柚', 'description': '红心柚子+茶底，酸甜开胃', 'price': 15.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '红柚', 'image_keyword': '满杯红柚茶'},
        {'name': '芒果烧仙草', 'description': '芒果果肉+仙草，清甜爽口', 'price': 14.0, 'category': '水果茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芒果、仙草', 'image_keyword': '芒果仙草'},
        {'name': '杨枝甘露', 'description': '芒果+椰浆+仙草，网红三拼', 'price': 15.0, 'category': '水果茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芒果、椰浆、仙草', 'image_keyword': '杨枝甘露奶茶'},
        {'name': '珍珠奶茶（大）', 'description': '经典珍珠奶茶，百喝不厌', 'price': 11.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '珍珠、奶茶', 'image_keyword': '珍珠奶茶'},
        {'name': '奶盖绿茶（大）', 'description': '咸奶盖+清爽绿茶，咸甜平衡', 'price': 14.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '绿茶、奶盖', 'image_keyword': '奶盖绿茶'},
    ],

    'yiheetang': [
        {'name': '蜂蜜柚子绿茶', 'description': '柚子香+蜂蜜甜+绿茶清', 'price': 12.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '柚子、蜂蜜、绿茶', 'image_keyword': '蜂蜜柚子绿茶'},
        {'name': '焦糖奶茶', 'description': '焦糖香气+浓醇奶茶', 'price': 12.0, 'category': '奶茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '焦糖、奶茶', 'image_keyword': '焦糖奶茶'},
        {'name': '满杯芒芒', 'description': '芒果果粒填满杯底，果香四溢', 'price': 14.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '芒果', 'image_keyword': '满杯芒果茶'},
        {'name': '珍珠奶茶（大）', 'description': '经典口味，浓郁奶香', 'price': 11.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '珍珠、奶茶', 'image_keyword': '珍珠奶茶'},
        {'name': '芝士奶茶（大）', 'description': '咸芝士奶盖+茶底，层次感强', 'price': 14.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芝士、奶茶', 'image_keyword': '芝士奶茶'},
        {'name': '百香双拼', 'description': '百香果+柠檬，双重酸爽', 'price': 13.0, 'category': '水果茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '百香果、柠檬', 'image_keyword': '百香果柠檬茶'},
        {'name': '椰香奶茶', 'description': '椰浆+奶茶，热带清香', 'price': 13.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '椰浆、奶茶', 'image_keyword': '椰香奶茶'},
    ],

    'guming': [
        {'name': '黄皮冻柠茶', 'description': '黄皮果+冻柠+红茶，岭南特色', 'price': 16.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '黄皮、柠檬、红茶', 'image_keyword': '黄皮冻柠茶'},
        {'name': '生椰茉莉', 'description': '椰浆+茉莉花茶，清新椰香', 'price': 17.0, 'category': '奶茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '椰浆、茉莉茶', 'image_keyword': '生椰茉莉奶茶'},
        {'name': '葡萄乌龙', 'description': '新鲜葡萄+乌龙茶底，果味清爽', 'price': 16.0, 'category': '水果茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '葡萄、乌龙茶', 'image_keyword': '葡萄乌龙茶'},
        {'name': '珍珠奶茶（大）', 'description': '浓香奶茶+弹牙珍珠', 'price': 12.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '珍珠、奶茶', 'image_keyword': '珍珠奶茶'},
        {'name': '芋圆奶茶', 'description': '手工芋圆+奶茶底', 'price': 14.0, 'category': '奶茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芋圆、奶茶', 'image_keyword': '芋圆奶茶'},
        {'name': '芒芒甘露（大）', 'description': '芒果+椰浆+西米，甜蜜满满', 'price': 17.0, 'category': '水果茶', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芒果、椰浆', 'image_keyword': '芒果甘露奶茶'},
        {'name': '丝绒燕麦拿铁', 'description': '燕麦奶+咖啡，健康低卡', 'price': 17.0, 'category': '咖啡', 'is_recommended': True, 'is_spicy': False, 'ingredients': '燕麦奶、咖啡', 'image_keyword': '燕麦拿铁'},
    ],

    'haidilao': [
        {'name': '番茄锅底', 'description': '新鲜番茄熬制，酸甜开胃', 'price': 38.0, 'category': '锅底', 'is_recommended': True, 'is_spicy': False, 'ingredients': '番茄', 'image_keyword': '海底捞番茄锅'},
        {'name': '麻辣锅底', 'description': '正宗四川麻辣，香辣过瘾', 'price': 38.0, 'category': '锅底', 'is_recommended': True, 'is_spicy': True, 'ingredients': '辣椒、花椒', 'image_keyword': '海底捞麻辣锅'},
        {'name': '菌汤锅底', 'description': '多种菌菇慢炖，鲜美浓郁', 'price': 38.0, 'category': '锅底', 'is_recommended': False, 'is_spicy': False, 'ingredients': '菌菇', 'image_keyword': '菌汤锅底'},
        {'name': '雪花牛肉', 'description': '高品质雪花牛肉，入口即化', 'price': 78.0, 'category': '涮品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉', 'image_keyword': '雪花牛肉火锅'},
        {'name': '原切牛肉', 'description': '整块牛肉现切，口感鲜嫩', 'price': 68.0, 'category': '涮品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '牛肉', 'image_keyword': '原切牛肉涮锅'},
        {'name': '毛肚', 'description': '脆爽毛肚，7上8下最嫩', 'price': 58.0, 'category': '涮品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肚', 'image_keyword': '毛肚火锅'},
        {'name': '羔羊肉', 'description': '内蒙羔羊，肉质鲜嫩无膻味', 'price': 52.0, 'category': '涮品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '羊肉', 'image_keyword': '羊肉卷火锅'},
        {'name': '虾滑', 'description': '鲜虾手打，弹牙爽口', 'price': 48.0, 'category': '涮品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '虾', 'image_keyword': '虾滑火锅'},
        {'name': '鸭血豆腐', 'description': '嫩滑鸭血+豆腐，经典搭配', 'price': 18.0, 'category': '涮品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸭血、豆腐', 'image_keyword': '鸭血豆腐'},
        {'name': '油条', 'description': '酥脆油条泡火锅汤，绝了', 'price': 8.0, 'category': '小食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '面粉', 'image_keyword': '油条'},
        {'name': '麻酱碗', 'description': '芝麻酱+蒜泥+葱花，配方独特', 'price': 8.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芝麻酱、蒜', 'image_keyword': '火锅蘸料麻酱'},
    ],

    'xiabu': [
        {'name': '麻辣锅底', 'description': '香辣浓郁，越涮越香', 'price': 28.0, 'category': '锅底', 'is_recommended': True, 'is_spicy': True, 'ingredients': '辣椒', 'image_keyword': '呷哺呷哺麻辣锅'},
        {'name': '番茄锅底', 'description': '番茄酸甜，百搭涮品', 'price': 28.0, 'category': '锅底', 'is_recommended': False, 'is_spicy': False, 'ingredients': '番茄', 'image_keyword': '番茄锅底'},
        {'name': '清汤锅底', 'description': '清淡滋补，原汁原味', 'price': 18.0, 'category': '锅底', 'is_recommended': False, 'is_spicy': False, 'ingredients': '骨汤', 'image_keyword': '清汤锅底'},
        {'name': '肥牛卷', 'description': '雪花肥牛，口感鲜嫩滑腻', 'price': 36.0, 'category': '涮品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉', 'image_keyword': '肥牛卷火锅'},
        {'name': '羊肉卷', 'description': '内蒙古羔羊，鲜嫩无膻', 'price': 32.0, 'category': '涮品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '羊肉', 'image_keyword': '羊肉卷火锅'},
        {'name': '毛肚', 'description': '脆嫩毛肚，下锅即熟', 'price': 38.0, 'category': '涮品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '牛肚', 'image_keyword': '毛肚火锅'},
        {'name': '单人套餐', 'description': '锅底+肉类+蔬菜+主食+饮料', 'price': 55.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛羊肉、蔬菜', 'image_keyword': '呷哺呷哺套餐'},
        {'name': '柠檬水', 'description': '清爽柠檬水，解辣开胃', 'price': 10.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '柠檬', 'image_keyword': '柠檬水'},
        {'name': '小料自选（每人）', 'description': '芝麻酱、沙茶酱、蒜泥等任选', 'price': 6.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '各类调料', 'image_keyword': '火锅蘸料'},
    ],

    'xiaolongkan': [
        {'name': '经典红汤锅底', 'description': '小龙坎秘制红汤，香辣浓郁', 'price': 38.0, 'category': '锅底', 'is_recommended': True, 'is_spicy': True, 'ingredients': '辣椒、花椒', 'image_keyword': '小龙坎红汤'},
        {'name': '麻辣鸳鸯锅底', 'description': '红汤+清汤，辣不辣都能涮', 'price': 48.0, 'category': '锅底', 'is_recommended': True, 'is_spicy': True, 'ingredients': '辣椒、骨汤', 'image_keyword': '鸳鸯锅火锅'},
        {'name': '极品肥牛', 'description': '高品质肥牛，入口即化', 'price': 68.0, 'category': '涮品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉', 'image_keyword': '肥牛卷火锅'},
        {'name': '黄喉', 'description': '脆爽黄喉，口感独特', 'price': 48.0, 'category': '涮品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '猪心管', 'image_keyword': '黄喉火锅'},
        {'name': '毛肚', 'description': '正宗毛肚，脆嫩爽口', 'price': 52.0, 'category': '涮品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肚', 'image_keyword': '毛肚火锅'},
        {'name': '虾滑', 'description': '鲜虾手打，弹性十足', 'price': 52.0, 'category': '涮品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '虾', 'image_keyword': '虾滑火锅'},
        {'name': '苕皮', 'description': '红薯粉皮，吸汁入味', 'price': 16.0, 'category': '涮品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '红薯粉', 'image_keyword': '苕皮火锅'},
        {'name': '油条', 'description': '金黄酥脆，蘸汤超香', 'price': 9.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '面粉', 'image_keyword': '油条'},
    ],

    'coucou': [
        {'name': '藤椒锅底', 'description': '藤椒清香，麻而不辣', 'price': 48.0, 'category': '锅底', 'is_recommended': True, 'is_spicy': False, 'ingredients': '藤椒', 'image_keyword': '藤椒锅底'},
        {'name': '番茄锅底', 'description': '酸甜番茄，百搭万物', 'price': 38.0, 'category': '锅底', 'is_recommended': False, 'is_spicy': False, 'ingredients': '番茄', 'image_keyword': '番茄锅底'},
        {'name': '菌汤锅底', 'description': '菌菇精华，鲜美无比', 'price': 48.0, 'category': '锅底', 'is_recommended': False, 'is_spicy': False, 'ingredients': '菌菇', 'image_keyword': '菌汤锅底'},
        {'name': '澳洲牛肉', 'description': '进口澳洲牛肉，鲜嫩多汁', 'price': 78.0, 'category': '涮品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉', 'image_keyword': '澳洲牛肉涮锅'},
        {'name': '牛舌', 'description': '切片牛舌，口感独特软嫩', 'price': 88.0, 'category': '涮品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛舌', 'image_keyword': '牛舌火锅'},
        {'name': '毛肚', 'description': '脆嫩毛肚，涮烫后口感最佳', 'price': 58.0, 'category': '涮品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '牛肚', 'image_keyword': '毛肚火锅'},
        {'name': '珍珠奶茶', 'description': '凑凑专属奶茶，搭配火锅独特', 'price': 18.0, 'category': '奶茶', 'is_recommended': True, 'is_spicy': False, 'ingredients': '珍珠、奶茶', 'image_keyword': '珍珠奶茶'},
        {'name': '鸭血豆腐', 'description': '嫩滑鸭血豆腐，经典搭配', 'price': 18.0, 'category': '涮品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸭血、豆腐', 'image_keyword': '鸭血豆腐'},
    ],

    'yoshinoya': [
        {'name': '牛丼（中）', 'description': '吉野家经典，牛肉+洋葱+特制酱汁', 'price': 21.0, 'category': '日式料理', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、洋葱、米饭', 'image_keyword': '吉野家牛丼'},
        {'name': '猪丼（中）', 'description': '嫩滑猪肉片+姜汁酱，日式风味', 'price': 18.0, 'category': '日式料理', 'is_recommended': False, 'is_spicy': False, 'ingredients': '猪肉、米饭', 'image_keyword': '吉野家猪丼'},
        {'name': '鸡丼（中）', 'description': '嫩鸡肉+蛋，亲子丼风味', 'price': 18.0, 'category': '日式料理', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡肉、鸡蛋、米饭', 'image_keyword': '鸡肉丼饭'},
        {'name': '鲑鱼丼（中）', 'description': '鲜美鲑鱼+米饭，海鲜清香', 'price': 23.0, 'category': '日式料理', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鲑鱼、米饭', 'image_keyword': '鲑鱼丼饭'},
        {'name': '牛丼定食套餐', 'description': '牛丼+味噌汤+小菜', 'price': 33.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、米饭、味噌', 'image_keyword': '吉野家定食'},
        {'name': '味噌汤', 'description': '日式经典味噌汤，暖胃暖心', 'price': 5.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '味噌、豆腐', 'image_keyword': '味噌汤'},
        {'name': '茶碗蒸', 'description': '嫩滑蛋羹，日式温润口感', 'price': 9.0, 'category': '小食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡蛋', 'image_keyword': '茶碗蒸'},
        {'name': '乌龙茶', 'description': '清香乌龙，搭配丼饭最佳', 'price': 7.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '乌龙茶', 'image_keyword': '乌龙茶'},
    ],

    'ajisen': [
        {'name': '豚骨拉面', 'description': '猪骨慢熬12小时，汤底浓郁醇厚', 'price': 38.0, 'category': '拉面', 'is_recommended': True, 'is_spicy': False, 'ingredients': '猪骨、拉面', 'image_keyword': '味千豚骨拉面'},
        {'name': '叉烧拉面', 'description': '豚骨汤底+厚切叉烧，鲜嫩入味', 'price': 42.0, 'category': '拉面', 'is_recommended': True, 'is_spicy': False, 'ingredients': '叉烧、猪骨汤、拉面', 'image_keyword': '叉烧拉面'},
        {'name': '海鲜拉面', 'description': '虾、蟹、贝类混搭，鲜味十足', 'price': 45.0, 'category': '拉面', 'is_recommended': False, 'is_spicy': False, 'ingredients': '海鲜、拉面', 'image_keyword': '海鲜拉面'},
        {'name': '味千酱油面', 'description': '清淡酱油汤底，原汁原味', 'price': 36.0, 'category': '拉面', 'is_recommended': False, 'is_spicy': False, 'ingredients': '酱油、拉面', 'image_keyword': '酱油拉面'},
        {'name': '乌冬面', 'description': '粗韧乌冬，劲道爽滑', 'price': 35.0, 'category': '乌冬', 'is_recommended': False, 'is_spicy': False, 'ingredients': '乌冬面', 'image_keyword': '乌冬面'},
        {'name': '拉面套餐', 'description': '豚骨拉面+饺子+饮料', 'price': 52.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '拉面、饺子', 'image_keyword': '味千拉面套餐'},
        {'name': '煎饺（6个）', 'description': '底部煎脆，内馅鲜美多汁', 'price': 18.0, 'category': '小食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '猪肉、韭菜', 'image_keyword': '煎饺'},
        {'name': '溏心蛋', 'description': '半熟蛋黄，浸泡酱油汁', 'price': 8.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡蛋、酱油', 'image_keyword': '溏心蛋'},
        {'name': '可乐', 'description': '清爽冰镇可乐', 'price': 8.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '碳酸饮料', 'image_keyword': '可口可乐'},
    ],

    'marugame': [
        {'name': '釜玉乌冬', 'description': '温热乌冬+生鸡蛋+酱油，日本国民美食', 'price': 22.0, 'category': '乌冬', 'is_recommended': True, 'is_spicy': False, 'ingredients': '乌冬、鸡蛋', 'image_keyword': '釜玉乌冬面'},
        {'name': '明太子黄油乌冬', 'description': '明太子+黄油+乌冬，浓郁鲜美', 'price': 28.0, 'category': '乌冬', 'is_recommended': True, 'is_spicy': False, 'ingredients': '明太子、黄油、乌冬', 'image_keyword': '明太子黄油乌冬'},
        {'name': '肉肉乌冬', 'description': '牛肉+葱花+特制酱汁，大口过瘾', 'price': 32.0, 'category': '乌冬', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、乌冬', 'image_keyword': '牛肉乌冬面'},
        {'name': '咖喱乌冬', 'description': '日式咖喱汤底，香浓顺滑', 'price': 30.0, 'category': '乌冬', 'is_recommended': False, 'is_spicy': False, 'ingredients': '咖喱、乌冬', 'image_keyword': '咖喱乌冬面'},
        {'name': '炸虾天妇罗', 'description': '酥脆炸虾，面衣轻薄入味', 'price': 10.0, 'category': '天妇罗', 'is_recommended': True, 'is_spicy': False, 'ingredients': '虾', 'image_keyword': '炸虾天妇罗'},
        {'name': '炸鸡天妇罗', 'description': '多汁鸡肉，外酥内嫩', 'price': 8.0, 'category': '天妇罗', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡肉', 'image_keyword': '炸鸡天妇罗'},
        {'name': '炸蔬菜天妇罗', 'description': '时令蔬菜裹浆油炸，清脆爽口', 'price': 5.0, 'category': '天妇罗', 'is_recommended': False, 'is_spicy': False, 'ingredients': '蔬菜', 'image_keyword': '蔬菜天妇罗'},
        {'name': '饭团', 'description': '现捏日式饭团，多种口味', 'price': 8.0, 'category': '主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '米饭', 'image_keyword': '日式饭团'},
        {'name': '绿茶', 'description': '清爽绿茶，搭配乌冬最合适', 'price': 5.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '绿茶', 'image_keyword': '绿茶'},
    ],

    'saizeriya': [
        {'name': '米兰风味猪排', 'description': '香酥猪排，米兰传统烹饪法', 'price': 28.0, 'category': '主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '猪排', 'image_keyword': '萨莉亚米兰猪排'},
        {'name': '奶油蛋黄培根意面', 'description': '正宗卡邦尼拉，浓郁奶油口感', 'price': 25.0, 'category': '意面', 'is_recommended': True, 'is_spicy': False, 'ingredients': '意面、培根、奶油', 'image_keyword': '萨莉亚培根意面'},
        {'name': '意式肉酱面', 'description': '番茄肉酱+意面，传统意式风味', 'price': 22.0, 'category': '意面', 'is_recommended': False, 'is_spicy': False, 'ingredients': '意面、牛肉肉酱', 'image_keyword': '肉酱意面'},
        {'name': '玛格丽特披萨', 'description': '番茄+芝士+罗勒，简约经典', 'price': 28.0, 'category': '披萨', 'is_recommended': True, 'is_spicy': False, 'ingredients': '番茄、芝士', 'image_keyword': '玛格丽特披萨'},
        {'name': '意式肉酱披萨', 'description': '肉酱+芝士，丰盛满足', 'price': 32.0, 'category': '披萨', 'is_recommended': False, 'is_spicy': False, 'ingredients': '牛肉肉酱、芝士', 'image_keyword': '肉酱披萨'},
        {'name': '烤鸡腿', 'description': '烤至金黄，外脆内嫩', 'price': 32.0, 'category': '主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡腿', 'image_keyword': '烤鸡腿'},
        {'name': '凯撒沙拉', 'description': '新鲜罗马生菜+帕玛森芝士+凯撒酱', 'price': 18.0, 'category': '小食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '生菜、芝士', 'image_keyword': '凯撒沙拉'},
        {'name': '蒜香虾', 'description': '大虾+蒜香黄油，鲜嫩入味', 'price': 26.0, 'category': '小食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '虾、大蒜', 'image_keyword': '蒜香虾'},
        {'name': '软饮（无限续杯）', 'description': '可乐/雪碧/橙汁，随意续杯', 'price': 6.0, 'category': '饮料', 'is_recommended': True, 'is_spicy': False, 'ingredients': '碳酸饮料', 'image_keyword': '萨莉亚饮料'},
        {'name': '葡萄酒（杯）', 'description': '意大利进口餐酒，简单纯粹', 'price': 12.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '葡萄酒', 'image_keyword': '葡萄酒'},
    ],

    'kungfu': [
        {'name': '豉汁蒸排骨饭', 'description': '招牌蒸制，排骨嫩滑，豉香浓郁', 'price': 22.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '排骨、豆豉、米饭', 'image_keyword': '豉汁蒸排骨饭'},
        {'name': '招牌蒸肠粉', 'description': '米浆现蒸，薄而不破，鲜嫩爽滑', 'price': 16.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '米浆、猪肉', 'image_keyword': '真功夫蒸肠粉'},
        {'name': '卤鸡腿饭', 'description': '卤汁鸡腿+白米饭，家常好味道', 'price': 22.0, 'category': '中式主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡腿、米饭', 'image_keyword': '卤鸡腿饭'},
        {'name': '咖喱牛腩饭', 'description': '浓郁咖喱+软烂牛腩，香辣开胃', 'price': 24.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': True, 'ingredients': '牛腩、咖喱', 'image_keyword': '咖喱牛腩饭'},
        {'name': '蒸饭套餐', 'description': '主菜+例汤+饮料，均衡营养', 'price': 28.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '米饭、肉类', 'image_keyword': '快餐套餐'},
        {'name': '包点（叉烧包）', 'description': '松软叉烧包，早餐点心首选', 'price': 5.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '面粉、叉烧', 'image_keyword': '叉烧包'},
        {'name': '豆浆', 'description': '现磨豆浆，营养丰富', 'price': 8.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '大豆', 'image_keyword': '豆浆'},
    ],

    'laoxiangji': [
        {'name': '老乡炖鸡汤', 'description': '整只鸡慢炖，汤清味鲜', 'price': 22.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '土鸡、香菇', 'image_keyword': '老乡鸡炖鸡汤'},
        {'name': '土鸡汤泡饭', 'description': '鸡汤泡米饭，暖胃滋补', 'price': 26.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡汤、米饭', 'image_keyword': '鸡汤泡饭'},
        {'name': '卤鸡腿饭', 'description': '入味卤鸡腿+白米饭', 'price': 22.0, 'category': '中式主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡腿、米饭', 'image_keyword': '卤鸡腿饭'},
        {'name': '红烧肉饭', 'description': '肥而不腻，入口即化的红烧肉', 'price': 22.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '五花肉、米饭', 'image_keyword': '红烧肉饭'},
        {'name': '单人套餐', 'description': '主菜+例汤+小菜+米饭', 'price': 32.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡肉、米饭', 'image_keyword': '老乡鸡套餐'},
        {'name': '虎皮凤爪', 'description': '卤制凤爪，软糯入味', 'price': 16.0, 'category': '小食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡爪', 'image_keyword': '虎皮凤爪'},
        {'name': '皮蛋豆腐', 'description': '嫩豆腐+皮蛋，爽滑开胃', 'price': 12.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '皮蛋、豆腐', 'image_keyword': '皮蛋豆腐'},
        {'name': '骨汤', 'description': '猪骨熬制，浓白滋补', 'price': 10.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '猪骨', 'image_keyword': '骨头汤'},
    ],

    'damixiansheng': [
        {'name': '剁椒蒸排骨', 'description': '剁椒+排骨蒸制，香辣开胃', 'price': 23.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': True, 'ingredients': '排骨、剁椒', 'image_keyword': '剁椒蒸排骨饭'},
        {'name': '豉汁排骨饭', 'description': '豆豉香气浓郁，排骨鲜嫩多汁', 'price': 22.0, 'category': '中式主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '排骨、豆豉', 'image_keyword': '豉汁排骨饭'},
        {'name': '宫保鸡丁饭', 'description': '酸辣鲜香，经典川式炒鸡', 'price': 21.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': True, 'ingredients': '鸡胸肉、花生', 'image_keyword': '宫保鸡丁饭'},
        {'name': '番茄炒蛋饭', 'description': '家常味道，番茄蛋汁拌饭超香', 'price': 18.0, 'category': '中式主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '番茄、鸡蛋', 'image_keyword': '番茄炒蛋饭'},
        {'name': '单人套餐', 'description': '主菜+例汤+饮料', 'price': 28.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '米饭、肉类', 'image_keyword': '快餐套餐'},
        {'name': '凉拌黄瓜', 'description': '脆嫩黄瓜+蒜末+辣油，开胃爽口', 'price': 8.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '黄瓜、蒜', 'image_keyword': '凉拌黄瓜'},
        {'name': '鲜榨果汁', 'description': '新鲜水果现榨，维生素满满', 'price': 12.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '水果', 'image_keyword': '鲜榨果汁'},
    ],

    'countrystyle': [
        {'name': '重庆辣子鸡饭', 'description': '重庆经典，辣椒炒鸡块，麻辣鲜香', 'price': 22.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': True, 'ingredients': '鸡肉、辣椒', 'image_keyword': '重庆辣子鸡饭'},
        {'name': '川味红烧肉饭', 'description': '川式红烧肉，麻辣中带甜', 'price': 24.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': True, 'ingredients': '五花肉、米饭', 'image_keyword': '红烧肉饭'},
        {'name': '鱼香肉丝饭', 'description': '经典川菜，酸甜辣鲜一锅端', 'price': 20.0, 'category': '中式主食', 'is_recommended': False, 'is_spicy': True, 'ingredients': '猪肉、木耳', 'image_keyword': '鱼香肉丝饭'},
        {'name': '土豆炖牛肉饭', 'description': '软烂牛肉+绵糯土豆，家常滋味', 'price': 24.0, 'category': '中式主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '牛肉、土豆', 'image_keyword': '土豆炖牛肉饭'},
        {'name': '烤鸭饭', 'description': '脆皮烤鸭+白米饭，香而不腻', 'price': 22.0, 'category': '中式主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '烤鸭、米饭', 'image_keyword': '烤鸭饭'},
        {'name': '单人套餐', 'description': '主菜+米饭+小菜+汤', 'price': 30.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '肉类、米饭', 'image_keyword': '快餐套餐'},
        {'name': '泡菜', 'description': '酸辣脆嫩泡菜，开胃解腻', 'price': 4.0, 'category': '小食', 'is_recommended': False, 'is_spicy': True, 'ingredients': '蔬菜', 'image_keyword': '四川泡菜'},
    ],

    'yanggf': [
        {'name': '麻辣烫套餐', 'description': '自选食材+麻辣汤底，暖胃过瘾', 'price': 38.0, 'category': '麻辣烫', 'is_recommended': True, 'is_spicy': True, 'ingredients': '各类食材', 'image_keyword': '杨国福麻辣烫'},
        {'name': '牛肉片（份）', 'description': '嫩滑牛肉，涮烫后鲜嫩多汁', 'price': 28.0, 'category': '麻辣烫', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉', 'image_keyword': '麻辣烫牛肉'},
        {'name': '羊肉片（份）', 'description': '鲜嫩羊肉，涮烫快熟', 'price': 25.0, 'category': '麻辣烫', 'is_recommended': False, 'is_spicy': False, 'ingredients': '羊肉', 'image_keyword': '麻辣烫羊肉'},
        {'name': '宽粉', 'description': '红薯宽粉，吸汁入味Q弹', 'price': 10.0, 'category': '麻辣烫', 'is_recommended': True, 'is_spicy': False, 'ingredients': '红薯粉', 'image_keyword': '麻辣烫宽粉'},
        {'name': '豆腐', 'description': '嫩豆腐，吸满汤汁', 'price': 8.0, 'category': '麻辣烫', 'is_recommended': False, 'is_spicy': False, 'ingredients': '豆腐', 'image_keyword': '麻辣烫豆腐'},
        {'name': '虾（份）', 'description': '新鲜虾，烫熟后鲜甜弹牙', 'price': 18.0, 'category': '麻辣烫', 'is_recommended': False, 'is_spicy': False, 'ingredients': '虾', 'image_keyword': '麻辣烫虾'},
        {'name': '双人套餐', 'description': '两份麻辣烫+主食+饮料', 'price': 68.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': True, 'ingredients': '各类食材', 'image_keyword': '麻辣烫套餐'},
        {'name': '米饭', 'description': '搭配麻辣烫的白米饭', 'price': 2.0, 'category': '主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '大米', 'image_keyword': '米饭'},
    ],

    'zhangliang': [
        {'name': '麻辣烫（自选）', 'description': '张亮秘制骨汤底料，香辣鲜美', 'price': 35.0, 'category': '麻辣烫', 'is_recommended': True, 'is_spicy': True, 'ingredients': '各类食材', 'image_keyword': '张亮麻辣烫'},
        {'name': '牛肉片（份）', 'description': '嫩滑牛肉片，烫10秒最嫩', 'price': 25.0, 'category': '麻辣烫', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉', 'image_keyword': '麻辣烫牛肉'},
        {'name': '培根（份）', 'description': '薄切培根，烫后飘香', 'price': 25.0, 'category': '麻辣烫', 'is_recommended': False, 'is_spicy': False, 'ingredients': '培根', 'image_keyword': '麻辣烫培根'},
        {'name': '宽粉', 'description': 'Q弹宽粉，最受欢迎的加料', 'price': 9.0, 'category': '麻辣烫', 'is_recommended': True, 'is_spicy': False, 'ingredients': '红薯粉', 'image_keyword': '麻辣烫宽粉'},
        {'name': '豆腐', 'description': '嫩豆腐入汤，鲜嫩滑口', 'price': 7.0, 'category': '麻辣烫', 'is_recommended': False, 'is_spicy': False, 'ingredients': '豆腐', 'image_keyword': '麻辣烫豆腐'},
        {'name': '单人套餐', 'description': '麻辣烫+主食+饮料', 'price': 38.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': True, 'ingredients': '各类食材', 'image_keyword': '麻辣烫套餐'},
        {'name': '柠檬水', 'description': '清爽柠檬水，解辣神器', 'price': 8.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '柠檬', 'image_keyword': '柠檬水'},
    ],

    'hefu': [
        {'name': '和风牛肉面', 'description': '日式清汤底+厚切牛肉，温润鲜美', 'price': 38.0, 'category': '面食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、和风汤底', 'image_keyword': '和府捞面牛肉面'},
        {'name': '松露猪骨面', 'description': '松露香气+猪骨浓汤，高端风味', 'price': 42.0, 'category': '面食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '松露、猪骨、面条', 'image_keyword': '松露猪骨面'},
        {'name': '和府招牌牛肉面', 'description': '24小时炖制牛骨汤，牛肉软烂', 'price': 45.0, 'category': '面食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、牛骨汤', 'image_keyword': '和府招牌牛肉面'},
        {'name': '茄汁番茄面', 'description': '清爽番茄汤底，酸甜开胃', 'price': 32.0, 'category': '面食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '番茄、面条', 'image_keyword': '番茄面条'},
        {'name': '清汤猪骨面', 'description': '清淡猪骨汤，原汁原味', 'price': 30.0, 'category': '面食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '猪骨、面条', 'image_keyword': '清汤面条'},
        {'name': '面+小食套餐', 'description': '任选一碗面+溏心蛋+小菜', 'price': 52.0, 'category': '套餐', 'is_recommended': True, 'is_spicy': False, 'ingredients': '面条、鸡蛋', 'image_keyword': '面条套餐'},
        {'name': '溏心卤蛋', 'description': '半熟蛋黄，浸泡酱汁入味', 'price': 8.0, 'category': '小食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡蛋', 'image_keyword': '溏心蛋'},
        {'name': '香辣小土豆', 'description': '软糯小土豆+香辣酱，超下饭', 'price': 18.0, 'category': '小食', 'is_recommended': False, 'is_spicy': True, 'ingredients': '土豆', 'image_keyword': '香辣小土豆'},
        {'name': '乌梅汁', 'description': '酸甜乌梅汁，古法配方', 'price': 12.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '乌梅', 'image_keyword': '乌梅汁'},
    ],

    'yujian': [
        {'name': '遇见招牌面', 'description': '重庆秘制辣酱+猪杂+面条，地道巴渝味', 'price': 26.0, 'category': '面食', 'is_recommended': True, 'is_spicy': True, 'ingredients': '猪杂、面条', 'image_keyword': '重庆小面'},
        {'name': '麻辣小面', 'description': '麻辣汤底+韭菜+榨菜，简单过瘾', 'price': 22.0, 'category': '面食', 'is_recommended': True, 'is_spicy': True, 'ingredients': '面条、麻辣汤', 'image_keyword': '麻辣小面'},
        {'name': '肥肠面', 'description': '入味肥肠+特制汤底，浓郁香辣', 'price': 28.0, 'category': '面食', 'is_recommended': False, 'is_spicy': True, 'ingredients': '肥肠、面条', 'image_keyword': '肥肠面'},
        {'name': '番茄鸡蛋面', 'description': '酸甜番茄+鸡蛋，清爽不辣', 'price': 20.0, 'category': '面食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '番茄、鸡蛋、面条', 'image_keyword': '番茄鸡蛋面'},
        {'name': '红烧牛肉面', 'description': '慢炖牛肉+红烧汤底，浓香扑鼻', 'price': 28.0, 'category': '面食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、面条', 'image_keyword': '红烧牛肉面'},
        {'name': '抄手（碗）', 'description': '鲜肉馅抄手+红油，滑嫩爽口', 'price': 15.0, 'category': '小食', 'is_recommended': True, 'is_spicy': True, 'ingredients': '猪肉、面皮', 'image_keyword': '重庆抄手'},
        {'name': '芝麻凉面', 'description': '芝麻酱+黄瓜丝+凉面，夏日必备', 'price': 15.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '面条、芝麻酱', 'image_keyword': '芝麻凉面'},
        {'name': '冰峰橙汁', 'description': '西安经典汽水，酸甜爽口', 'price': 7.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '橙汁汽水', 'image_keyword': '橙汁饮料'},
    ],

    'wuye': [
        {'name': '五爷招牌拌面', 'description': '秘制酱料+劲道面条，一拌即香', 'price': 22.0, 'category': '面食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '面条、秘制酱', 'image_keyword': '五爷拌面'},
        {'name': '牛肉拌面', 'description': '厚切卤牛肉+招牌拌面酱', 'price': 26.0, 'category': '面食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉、面条', 'image_keyword': '牛肉拌面'},
        {'name': '芝麻酱拌面', 'description': '香浓芝麻酱+黄瓜+花生碎', 'price': 20.0, 'category': '面食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '芝麻酱、面条', 'image_keyword': '芝麻酱拌面'},
        {'name': '香辣肉丝拌面', 'description': '辣味肉丝+特调酱料，越拌越香', 'price': 22.0, 'category': '面食', 'is_recommended': False, 'is_spicy': True, 'ingredients': '猪肉丝、面条', 'image_keyword': '香辣肉丝面'},
        {'name': '鸡蛋拌面', 'description': '溏心蛋+拌面酱，简单鲜美', 'price': 18.0, 'category': '面食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡蛋、面条', 'image_keyword': '鸡蛋拌面'},
        {'name': '夫妻肺片', 'description': '经典川式冷菜，麻辣鲜香', 'price': 22.0, 'category': '小食', 'is_recommended': True, 'is_spicy': True, 'ingredients': '牛肉、牛杂', 'image_keyword': '夫妻肺片'},
        {'name': '凉拌黄瓜', 'description': '脆嫩黄瓜+辣油蒜汁，爽口开胃', 'price': 8.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '黄瓜', 'image_keyword': '凉拌黄瓜'},
        {'name': '卤蛋', 'description': '卤汁入味，蛋香浓郁', 'price': 4.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '鸡蛋', 'image_keyword': '卤蛋'},
    ],

    'xibei': [
        {'name': '功夫鱼', 'description': '西贝特色，整条鱼现做，鲜嫩爽滑', 'price': 78.0, 'category': '主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '草鱼', 'image_keyword': '西贝功夫鱼'},
        {'name': '草原羔羊腿', 'description': '整只羔羊腿烤制，肉嫩无膻', 'price': 128.0, 'category': '主食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '羔羊腿', 'image_keyword': '烤羊腿'},
        {'name': '手工莜面', 'description': '内蒙古莜麦手工制作，筋道耐嚼', 'price': 25.0, 'category': '面食', 'is_recommended': True, 'is_spicy': False, 'ingredients': '莜麦面', 'image_keyword': '莜面'},
        {'name': '炒羊肉', 'description': '大火爆炒内蒙羊肉，鲜嫩多汁', 'price': 62.0, 'category': '主食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '羊肉', 'image_keyword': '炒羊肉'},
        {'name': '莜面窝窝', 'description': '莜麦面做成的传统窝窝头', 'price': 22.0, 'category': '面食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '莜麦面', 'image_keyword': '莜面窝窝'},
        {'name': '奶酪', 'description': '内蒙古纯手工奶酪，浓郁奶香', 'price': 22.0, 'category': '甜品', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛奶', 'image_keyword': '内蒙古奶酪'},
        {'name': '炸糕', 'description': '外酥内软的传统糕点', 'price': 18.0, 'category': '甜品', 'is_recommended': False, 'is_spicy': False, 'ingredients': '糯米、豆沙', 'image_keyword': '炸糕'},
        {'name': '酸梅汤', 'description': '古法酸梅汤，酸甜解腻', 'price': 15.0, 'category': '饮料', 'is_recommended': True, 'is_spicy': False, 'ingredients': '乌梅、山楂', 'image_keyword': '酸梅汤'},
        {'name': '奶茶', 'description': '内蒙古传统奶茶，咸香浓郁', 'price': 18.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '砖茶、牛奶', 'image_keyword': '内蒙古奶茶'},
    ],

    'muwu': [
        {'name': '羊肉串', 'description': '内蒙羔羊肉，外焦里嫩，撒孜然更香', 'price': 5.0, 'category': '烧烤', 'is_recommended': True, 'is_spicy': True, 'ingredients': '羊肉', 'image_keyword': '羊肉串烧烤'},
        {'name': '牛肉串', 'description': '精选牛肉，鲜嫩多汁', 'price': 8.0, 'category': '烧烤', 'is_recommended': True, 'is_spicy': False, 'ingredients': '牛肉', 'image_keyword': '牛肉串烧烤'},
        {'name': '烤鸡翅', 'description': '秘制腌制鸡翅，外焦里嫩', 'price': 12.0, 'category': '烧烤', 'is_recommended': True, 'is_spicy': False, 'ingredients': '鸡翅', 'image_keyword': '烤鸡翅'},
        {'name': '烤生蚝', 'description': '蒜蓉+粉丝+生蚝，鲜美多汁', 'price': 12.0, 'category': '烧烤', 'is_recommended': True, 'is_spicy': False, 'ingredients': '生蚝、蒜蓉', 'image_keyword': '烤生蚝'},
        {'name': '烤茄子', 'description': '茄子烤软+蒜蓉酱，香软入味', 'price': 12.0, 'category': '烧烤', 'is_recommended': False, 'is_spicy': False, 'ingredients': '茄子', 'image_keyword': '烤茄子'},
        {'name': '烤金针菇', 'description': '金针菇+黄油，鲜嫩滑爽', 'price': 10.0, 'category': '烧烤', 'is_recommended': False, 'is_spicy': False, 'ingredients': '金针菇', 'image_keyword': '烤金针菇'},
        {'name': '烤玉米', 'description': '整根玉米烤制，焦香甜糯', 'price': 8.0, 'category': '烧烤', 'is_recommended': False, 'is_spicy': False, 'ingredients': '玉米', 'image_keyword': '烤玉米'},
        {'name': '凉菜拼盘', 'description': '多种凉菜搭配，开胃解腻', 'price': 28.0, 'category': '小食', 'is_recommended': False, 'is_spicy': False, 'ingredients': '蔬菜', 'image_keyword': '凉菜拼盘'},
        {'name': '扎啤（中）', 'description': '冰镇扎啤，烧烤最佳搭档', 'price': 18.0, 'category': '饮料', 'is_recommended': True, 'is_spicy': False, 'ingredients': '啤酒', 'image_keyword': '扎啤'},
        {'name': '柠檬水', 'description': '鲜柠檬水，清爽解辣', 'price': 12.0, 'category': '饮料', 'is_recommended': False, 'is_spicy': False, 'ingredients': '柠檬', 'image_keyword': '柠檬水'},
    ],
}
